### ISSUE TITLE
when I run make during installation, I enconter a error. 

### ISSUE THREAD

**Issue by fanqingsong** [cea-hpc/modules#298] opened 2019-11-06 05:46 UTC
**error is as below, could you help me? **
mv -f .deps/modulecmd-locate_module.Tpo .deps/modulecmd-locate_module.Po
gcc -DHAVE_CONFIG_H -I.    -I/usr/local/include  -g -O2 -MT modulecmd-utility.o -MD -MP -MF .deps/modulecmd-utility.Tpo -c -o modulecmd-utility.o `test -f 'utility.c' || echo './'`utility.c
utility.c: In function 'output_set_variable':
utility.c:1048:56: error: expected expression before ')' token
      if(( lmfiles_len = strlen(escaped)) > LMSPLIT_SIZE) {
                                                        ^
utility.c:1055:39: error: expected expression before ')' token
      while( lmfiles_len > LMSPLIT_SIZE) {
                                       ^
utility.c:1057:16: error: 'buffer' undeclared (first use in this function)
       strncpy( buffer, ( escaped + count*LMSPLIT_SIZE ),
                ^~~~~~
utility.c:1057:16: note: each undeclared identifier is reported only once for each function it appears in
utility.c:1058:21: error: expected expression before ')' token
         LMSPLIT_SIZE);
                     ^
utility.c:1059:23: error: expected expression before ']' token
   buffer[ LMSPLIT_SIZE] = '\0';
                       ^
utility.c:1064:30: error: expected expression before ';' token
   lmfiles_len -= LMSPLIT_SIZE;
                              ^
utility.c:1070:36: error: expected expression before ')' token
       (escaped + count*LMSPLIT_SIZE), shell_cmd_separator);
                                    ^
Makefile:1103: recipe for target 'modulecmd-utility.o' failed
make[1]: *** [modulecmd-utility.o] Error 1
make[1]: Leaving directory '/home/efnxqng/software/modules/modules-4.2.1/compat'
Makefile:171: recipe for target 'compat/modulecmd' failed
make: *** [compat/modulecmd] Error 2

**Comment by xdelaruelle** [comment] 2019-11-06 05:58
Could you please provide the `./configure` and `make` commands you type with all argument passed to obtain this error. And also provide the `/home/efnxqng/software/modules/modules-4.2.1/compat/config.log` generated by the `./configure` step. All of this will help to reproduce the issue and understand what happen.

**Comment by xdelaruelle** [comment] 2019-11-21 23:53
@fanqingsong commands you typed and content of `/home/efnxqng/software/modules/modules-4.2.1/compat/config.log` is required to help you here. I am closing this as it cannot be reproduced. I will reopen it if the necessary information to reproduce the issue is provided.

**Closed by xdelaruelle** 2019-11-21 23:53 UTC
Labels: cannot reproduce, need more info
