### ISSUE TITLE
module defaults to dot

### ISSUE THREAD

**Issue by yankee14aaaa** [cea-hpc/modules#134] opened 2017-10-13 08:05 UTC
When I load a module with a full path (e.g. no module use command), the modulepath defaults to "dot".
Then later commands will scan the full hierarchy for modules.
e.g. 
cd
module load $HOME/modulefiles/init
module list  
> scan full disk  $HOME for valid modules, which takes 1/2hour even if "dot" is not in the module path.
[module_list_log.txt](https://github.com/cea-hpc/modules/files/1381820/module_list_log.txt)

**Comment by xdelaruelle** [comment] 2017-10-13 12:56
Thanks for your report. This issue has been spotted and fixed in current development tree. The fix will be part of next version (v4.0.0).

Duplicate of #132

**Closed by xdelaruelle** 2017-10-13 12:56 UTC
