### ISSUE TITLE
run "module add tool/version" command generated one "-50000000 06:36 add" history item

### ISSUE THREAD

**Issue by benwanlin** [cea-hpc/modules#277] opened 2019-06-04 06:38 UTC
under Tcsh environment, run "module add tool/version" command generated "-50000000 06:36 add" history item.

**Comment by xdelaruelle** [comment] 2019-06-04 07:49
More informations are needed to qualify this issue. Could you provide the output generated by the following commands:

```
$ module -V
$ alias
$ env
$ set
```

And also the content of the `tool/version` modulefile and any tcsh shell configuration file you use (like `~/.cshrc`, `~/.login`, `~/.tcshrc` and so on).

**Comment by benwanlin** [comment] 2019-06-04 08:21
Currently I know the module version is 4.2.4. Once I get home I will provide other information needed from my environment. 
Thanks.

**Comment by xdelaruelle** [comment] 2019-06-26 05:24
@benwanlin I would be glad to look at this issue however with the current details provided I cannot do anything. Could you please provide the information detailed in my previous comment?

**Comment by xdelaruelle** [comment] 2019-07-12 08:01
@benwanlin I am closing this issue as there is no element provided to qualify it. I will re-open the issue in case some additional element is provided to address the issue

**Comment by xdelaruelle** [comment] 2019-08-11 07:45
Got some clue to reproduce this issue from [this mailing-list thread](https://sourceforge.net/p/modules/mailman/message/36641816/), which exposes the same issue.

The issue can be reproduced on an EL7 system, with default configuration. Seems related to the version of tcsh on this OS (tcsh-6.18.01-15). It cannot be reproduced on a Fedora system which ships tcsh-6.20.00-9.

Issue comes from the quote modifier (`:q`) used to pass arguments received by the `module` alias to the `modulecmd.tcl` script.

**Comment by xdelaruelle** [comment] 2019-08-12 11:43
The strange history entries vanish from the `history` command output after 18_03 release. [This code change](https://github.com/tcsh-org/tcsh/commit/955c966ffebfb6d791c289b67681f84d4a53d580) makes these entries disappear from sight but they are still recorded in the history file:

```
#+1565531636
module load foo bar
#+1565531636
load foo bar#+1565531638
history
```

**Comment by xdelaruelle** [comment] 2019-08-12 19:57
Issue comes from the `module` alias definition:

    eval "`/usr/bin/tclsh /usr/share/Modules/libexec/modulecmd.tcl tcsh !*:q`"

From [this commit](https://github.com/cea-hpc/modules/commit/a3adb4b4a03418916761824c100fe1b321bdbbae), csh code generated by the modulecmd.tcl script was enclosed in double-quotes before passed to eval, which enables for instance the definition of aliases using curly braces in their syntax, like:

    set-alias foo {echo foo bar foo | awk '{ print \$3; }'}

With a more traditional `module` alias definition:

    eval `/usr/bin/tclsh /usr/share/Modules/libexec/modulecmd.tcl tcsh !*`

The command alias [3] cannot be set:

    $ module load ./testalias
    Missing }.
    $ module list
    No Modulefiles Currently Loaded.

Enclosing csh code generated by the modulecmd.tcl script in double-quotes before passing it to eval requires to correctly handle quoted arguments passed to the `module` alias. This is why the quote modifier `:q` is added to `!*`. And it seems that using `!*:q` within a backtick context `` leads to the erroneous history entries.

I am a bit torn here because restoring the previous syntax definition of the module alias would solve the issue reported here but it would restrain the capabilities for users to define shell aliases with characters that have a special meanings in csh.

**Comment by xdelaruelle** [comment] 2019-08-13 15:05
I have reported a bug against `tcsh`: https://bugs.astron.com/view.php?id=99

This issue does not affect `csh` on Solaris.

**Comment by xdelaruelle** [comment] 2019-09-16 15:04
There is no news on the bug reported upstream.

I will add a workaround that could be enabled via a configuration option. Current behavior will stay the default and to fix the Tcsh history issue the workaround should be enabled. Enabling this workaround will weaken shell code evaluation (regarding special characters used in shell alias definition for instance).

**Closed** 2019-09-17 03:31 UTC
